### PR TITLE
Merge auth pay

### LINKED ISSUE #40: FE: Sign in
- Code sign-in modal

### LINKED ISSUE #41: FE: Sign up
- Code sign-up modal

### LINKED ISSUE #42: FE: Add product to card
- Use js to create add to cart function

### LINKED ISSUE #44: FE: Cart page - left side

### LINKED ISSUE #45: FE: Cart page - right side

### LINKED ISSUE #46: FE: Payment page - left side

### LINKED ISSUE #47: FE: Payment page - right side

### PR DESCRIPTION
**Pull request by Boboiboy181**
closes #40 , #41 , #42, #44, #45, #46, #47

### CODE REVIEW

**Review by ThuyTienMango — COMMENTED** [review]
all okay

**Review by bchau2408 — APPROVED** [review]
okay

**Review by ThuyTienMango — APPROVED** [review]

**Review by MinhTu2509 — APPROVED** [review]
Ok het rui nha!!!

**Review by horralnguyen — APPROVED** [review]
done

**Pull request merged**
